### ISSUE TITLE
Android build fails in PR #11: Missing `using Android.Content.PM;` directive

### ISSUE THREAD

**Issue by Sktler** [Sktler/Aurora-os#12]
## Problem
The Android build is failing with compiler error CS0234 in `Aurora.Android/AuroraHomeActivity.cs`:

```
error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Aurora.Android'
```

This occurs at:
- Line 16: Multiple errors in the `[Activity]` attribute referencing `Android.Content.PM.ConfigChanges`
- Line 102: Error in `OnRequestPermissionsResult` method parameter type `Android.Content.PM.Permission[]?`

**Build log:** https://github.com/Sktler/Aurora-os/actions/runs/33997783275/job/101391846517?pr=11

## Root Cause
PR #11 added a new `OnRequestPermissionsResult` override that uses `Android.Content.PM.Permission[]?` and the `[Activity]` attribute uses `Android.Content.PM.ConfigChanges`, but the required `using Android.Content.PM;` directive is missing from the file.

## Solution
Add the following `using` directive to `Aurora.Android/AuroraHomeActivity.cs` at line 2 (with the other Android namespace imports):

```csharp
using Android.Content.PM;
```

**File location:** Aurora.Android/AuroraHomeActivity.cs, lines 1-12

**Updated imports should be:**
```csharp
using Android.App;
using Android.Content;
using Android.Content.PM;  // Add this line
using Android.Graphics;
using Android.Hardware;
using Android.Net;
using Android.OS;
using Android.Provider;
using Android.Views;
using Android.Widget;
using Aurora.Android.Services;
using Aurora.Android.Updates;
using Aurora.Core;
```

This resolves all 6 compiler errors (CS0234) preventing the build from completing.

## Related
- PR #11: Respect user permission choices
- File: `Aurora.Android/AuroraHomeActivity.cs`
- Workflow: `.github/workflows/android-build.yml`
